// <auto-generated />
using System;
using Cooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cooking.Infrastructure.Migrations
{
    [DbContext(typeof(CookingDbContext))]
    [Migration("20260929144740_RecipeDraftPendingCorrection")]
    partial class RecipeDraftPendingCorrection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cooking.Domain.Entities.Ingredients.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataSources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000001"),
                            Name = "Manual"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000002"),
                            Name = "LLM"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000003"),
                            Name = "FatSecret"
                        });
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Ingredients.IngredientCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseUnitId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CarbsPer100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBySourceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FatPer100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("NutritionSourceId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PieceWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PricePer100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ProteinPer100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBySourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NutritionSourceId");

                    b.ToTable("IngredientCatalog");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Ingredients.IngredientCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IngredientCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000001"),
                            Name = "Мясо"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000002"),
                            Name = "Птица"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000003"),
                            Name = "Рыба и морепродукты"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000004"),
                            Name = "Овощи"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000005"),
                            Name = "Фрукты"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000006"),
                            Name = "Крупы и бобовые"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000007"),
                            Name = "Молочные продукты"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000008"),
                            Name = "Яйца"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000009"),
                            Name = "Масла и жиры"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000010"),
                            Name = "Мучное и выпечка"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000011"),
                            Name = "Специи и приправы"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000012"),
                            Name = "Напитки"
                        });
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Ingredients.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MeasurementUnits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000001"),
                            Abbreviation = "г",
                            Name = "Грамм"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000002"),
                            Abbreviation = "мл",
                            Name = "Миллилитр"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000003"),
                            Abbreviation = "шт",
                            Name = "Штука"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000004"),
                            Abbreviation = "ст.л.",
                            Name = "Столовая ложка"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000005"),
                            Abbreviation = "ч.л.",
                            Name = "Чайная ложка"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000006"),
                            Abbreviation = "стак.",
                            Name = "Стакан"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000007"),
                            Abbreviation = "щеп.",
                            Name = "Щепотка"
                        });
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.Complexity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Complexities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000001"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000002"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000003"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplexityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CookingTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComplexityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SourceTypeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.RecipeDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingCorrection")
                        .HasColumnType("text");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("RecipeDrafts");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredientCatalogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IngredientCatalogId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TimerSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.SourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SourceTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Name = "Manual"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000002"),
                            Name = "Instagram"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000003"),
                            Name = "YouTube"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000004"),
                            Name = "Website"
                        });
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Tags.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TagTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TagTypeId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0001-000000000001"),
                            Name = "Завтрак",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0001-000000000002"),
                            Name = "Обед",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0001-000000000003"),
                            Name = "Ужин",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0001-000000000004"),
                            Name = "Перекус",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0001-000000000005"),
                            Name = "Десерт",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0002-000000000001"),
                            Name = "Русская",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0002-000000000002"),
                            Name = "Итальянская",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0002-000000000003"),
                            Name = "Азиатская",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0002-000000000004"),
                            Name = "Кавказская",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0002-000000000005"),
                            Name = "Средиземноморская",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0003-000000000001"),
                            Name = "Варка",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0003-000000000002"),
                            Name = "Жарка",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0003-000000000003"),
                            Name = "Запекание",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0003-000000000004"),
                            Name = "Тушение",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0003-000000000005"),
                            Name = "На пару",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0003-000000000006"),
                            Name = "Гриль",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0003-000000000007"),
                            Name = "Без готовки",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0004-000000000001"),
                            Name = "Вегетарианское",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0004-000000000002"),
                            Name = "Веганское",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0004-000000000003"),
                            Name = "Высокобелковое",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0004-000000000004"),
                            Name = "Низкоуглеводное",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0004-000000000005"),
                            Name = "Без глютена",
                            TagTypeId = new Guid("00000006-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Tags.TagType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TagTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000001"),
                            Name = "MealType"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000002"),
                            Name = "Cuisine"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000003"),
                            Name = "CookingMethod"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000004"),
                            Name = "Diet"
                        });
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Users.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Users.FamilyInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FamilyId");

                    b.ToTable("FamilyInvites");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Ingredients.IngredientCatalog", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Ingredients.MeasurementUnit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Ingredients.IngredientCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Ingredients.DataSource", "CreatedBySource")
                        .WithMany()
                        .HasForeignKey("CreatedBySourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Ingredients.DataSource", "NutritionSource")
                        .WithMany()
                        .HasForeignKey("NutritionSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnit");

                    b.Navigation("Category");

                    b.Navigation("CreatedBySource");

                    b.Navigation("NutritionSource");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.Recipe", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Recipes.Complexity", "Complexity")
                        .WithMany()
                        .HasForeignKey("ComplexityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Users.User", "CreatedByUser")
                        .WithMany("CreatedRecipes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Recipes.SourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complexity");

                    b.Navigation("CreatedByUser");

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.RecipeDraft", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Ingredients.IngredientCatalog", "IngredientCatalog")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Ingredients.MeasurementUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IngredientCatalog");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.RecipeStep", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Tags.RecipeTag", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Tags.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Tags.Tag", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Tags.TagType", "TagType")
                        .WithMany()
                        .HasForeignKey("TagTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TagType");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Users.FamilyInvite", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooking.Domain.Entities.Users.Family", "Family")
                        .WithMany("Invites")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Cooking.Domain.Entities.Users.Family", "Family")
                        .WithMany("Users")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Ingredients.IngredientCatalog", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("RecipeTags");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Tags.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Users.Family", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Cooking.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("CreatedRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
